{{- if and .Values.server.enabled .Values.server.ingress.enabled  }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
{{- with .Values.server.ingress.annotations }}
  annotations:
{{ toYaml .| indent 4 }}
{{- end }}
  labels:
  {{- include "vmalert.server.labels" . | nindent 4 }}
  {{ with .Values.server.ingress.extraLabels }}
{{ toYaml . | indent 4 }}
  {{ end }}
  name: {{ template "vmalert.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  {{- $serviceName := include "vmalert.server.fullname" . }}
  {{- range .Values.server.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
        - path: {{ .path }}
          backend:
            serviceName: {{ $serviceName }}
            servicePort: {{ .port | default "http"}}
    {{- end -}}
{{- with .Values.server.ingress.tls }}
  tls:
{{ toYaml . | indent 4 }}
{{- end -}}
{{- end -}}
